### ISSUE TITLE
Failed to adapt server configuration

### ISSUE THREAD

**Issue by Rocologo** [MarioWi/multicraft-docker#7]
I am testing this build, but I am having a problem. 

First time I run my docker-compose file everything works. I can create my first Minecraft server and play on it. But each time i stop the server and stop the containers and the restart the system I get this error

Failed to adapt server configuration

and the server cant start ??? 

I can see that It is something with the file permissions in servers/server1 and I guess I have made something wrong in my docker-compose.yml file 

```
 services:
   multicraft:
     build: 
       context: ./
       args:
         - USERID=99
         - GROUPID=100
         - USERNAME=christian
```
I dont understand how to use these three variables ?
